### ISSUE TITLE
Features Missing 2

### ISSUE THREAD

**Issue by itsShivam2** [shardul523/traffic-citation-api#2]
* Role to the frontend
* Vehicle model inconsistency
* Create challan officer Id inconsistency.
* Get officer challans route

**Comment by shardul523** [comment]
* Sent role to frontend
* Fixed vehicle model inconsistency

**Comment by shardul523** [comment]
Fixed create challan officer Id inconsistency.

**Comment by shardul523** [comment]
Added get officer challans route
